/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace GestorLicitaciones {
  export type PropuestaStruct = {
    proponente: AddressLike;
    hashPropuesta: string;
    timestamp: BigNumberish;
  };

  export type PropuestaStructOutput = [
    proponente: string,
    hashPropuesta: string,
    timestamp: bigint
  ] & { proponente: string; hashPropuesta: string; timestamp: bigint };
}

export interface GestorLicitacionesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adjudicar"
      | "contadorLicitaciones"
      | "crearLicitacion"
      | "getPropuestas"
      | "licitaciones"
      | "owner"
      | "presentarPropuesta"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EstadoCambiado"
      | "LicitacionCreada"
      | "OwnershipTransferred"
      | "PropuestaPresentada"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "adjudicar",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contadorLicitaciones",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "crearLicitacion",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPropuestas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "licitaciones",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "presentarPropuesta",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "adjudicar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contadorLicitaciones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "crearLicitacion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPropuestas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "licitaciones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "presentarPropuesta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace EstadoCambiadoEvent {
  export type InputTuple = [id: BigNumberish, nuevoEstado: BigNumberish];
  export type OutputTuple = [id: bigint, nuevoEstado: bigint];
  export interface OutputObject {
    id: bigint;
    nuevoEstado: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LicitacionCreadaEvent {
  export type InputTuple = [id: BigNumberish, cuce: string];
  export type OutputTuple = [id: bigint, cuce: string];
  export interface OutputObject {
    id: bigint;
    cuce: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropuestaPresentadaEvent {
  export type InputTuple = [
    idLicitacion: BigNumberish,
    proponente: AddressLike
  ];
  export type OutputTuple = [idLicitacion: bigint, proponente: string];
  export interface OutputObject {
    idLicitacion: bigint;
    proponente: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GestorLicitaciones extends BaseContract {
  connect(runner?: ContractRunner | null): GestorLicitaciones;
  waitForDeployment(): Promise<this>;

  interface: GestorLicitacionesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adjudicar: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  contadorLicitaciones: TypedContractMethod<[], [bigint], "view">;

  crearLicitacion: TypedContractMethod<
    [_cuce: string, _descripcion: string, _hashDBC: string],
    [void],
    "nonpayable"
  >;

  getPropuestas: TypedContractMethod<
    [_idLicitacion: BigNumberish],
    [GestorLicitaciones.PropuestaStructOutput[]],
    "view"
  >;

  licitaciones: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, string] & {
        id: bigint;
        cuce: string;
        descripcion: string;
        estado: bigint;
        creador: string;
        hashDBC: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  presentarPropuesta: TypedContractMethod<
    [_idLicitacion: BigNumberish, _hashPropuesta: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adjudicar"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contadorLicitaciones"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "crearLicitacion"
  ): TypedContractMethod<
    [_cuce: string, _descripcion: string, _hashDBC: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPropuestas"
  ): TypedContractMethod<
    [_idLicitacion: BigNumberish],
    [GestorLicitaciones.PropuestaStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "licitaciones"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, string] & {
        id: bigint;
        cuce: string;
        descripcion: string;
        estado: bigint;
        creador: string;
        hashDBC: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "presentarPropuesta"
  ): TypedContractMethod<
    [_idLicitacion: BigNumberish, _hashPropuesta: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "EstadoCambiado"
  ): TypedContractEvent<
    EstadoCambiadoEvent.InputTuple,
    EstadoCambiadoEvent.OutputTuple,
    EstadoCambiadoEvent.OutputObject
  >;
  getEvent(
    key: "LicitacionCreada"
  ): TypedContractEvent<
    LicitacionCreadaEvent.InputTuple,
    LicitacionCreadaEvent.OutputTuple,
    LicitacionCreadaEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PropuestaPresentada"
  ): TypedContractEvent<
    PropuestaPresentadaEvent.InputTuple,
    PropuestaPresentadaEvent.OutputTuple,
    PropuestaPresentadaEvent.OutputObject
  >;

  filters: {
    "EstadoCambiado(uint256,uint8)": TypedContractEvent<
      EstadoCambiadoEvent.InputTuple,
      EstadoCambiadoEvent.OutputTuple,
      EstadoCambiadoEvent.OutputObject
    >;
    EstadoCambiado: TypedContractEvent<
      EstadoCambiadoEvent.InputTuple,
      EstadoCambiadoEvent.OutputTuple,
      EstadoCambiadoEvent.OutputObject
    >;

    "LicitacionCreada(uint256,string)": TypedContractEvent<
      LicitacionCreadaEvent.InputTuple,
      LicitacionCreadaEvent.OutputTuple,
      LicitacionCreadaEvent.OutputObject
    >;
    LicitacionCreada: TypedContractEvent<
      LicitacionCreadaEvent.InputTuple,
      LicitacionCreadaEvent.OutputTuple,
      LicitacionCreadaEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PropuestaPresentada(uint256,address)": TypedContractEvent<
      PropuestaPresentadaEvent.InputTuple,
      PropuestaPresentadaEvent.OutputTuple,
      PropuestaPresentadaEvent.OutputObject
    >;
    PropuestaPresentada: TypedContractEvent<
      PropuestaPresentadaEvent.InputTuple,
      PropuestaPresentadaEvent.OutputTuple,
      PropuestaPresentadaEvent.OutputObject
    >;
  };
}
